### PR TITLE
Add instructions on how to use docker to run postgresql

### PR DESCRIPTION
**Pull request by HirotoShioi**
Add instruction on how to use Docker to run postgresql. 
This is much nicer since you can use postgresql without ever installing it on their local machine.

@parsonsmatt If you're interested, I can also, add `docker-compose.yml` file to the repo as well!

### CODE REVIEW

**Review by parsonsmatt — APPROVED** [review]
A `docker-compose.yml` file would be great! :smile:

**Comment by HirotoShioi** [comment]
Okay, it seems like the command I provided only installs docker and not docker-compose. 
Please don't merge yet!
Looking into it.

**Comment by HirotoShioi** [comment]
Fixed it's ready to be merged once CI passes!

**Comment by HirotoShioi** [comment]
@parsonsmatt It's ready to be merged!

**Pull request closed without merging**
